#!/bin/bash

options=(
    style=round
    # width=6.0
    width=8.0
    hidpi=on
    # active_color=0xffe2e2e3
    # inactive_color=0xff414550
    # active_color=0xffdcd7ba
    # inactive_color=0xff727169
    active_color=0xffe1e3e4
    inactive_color=0xff494d64
)

borders "${options[@]}"
