return {
    { "simrat39/symbols-outline.nvim", enabled = true },
    { "goolord/alpha-nvim", enabled = false },
    -- { "folke/edgy.nvim", enabled = false },
    { "zbirenbaum/copilot-cmp", enabled = false },
    { "sphamba/smear-cursor.nvim", enabled = false },
    { "yetone/avante.nvim", enabled = false },
    { "nvim-neo-tree/neo-tree.nvim", enabled = false },
    { "zaldih/themery.nvim", enabled = false },
    { "andweeb/presence.nvim", enabled = false },
    { "zbirenbaum/copilot.lua", enabled = false },
    -- { "folke/sidekick.nvim", enabled = false },
    { "typicode/bg.nvim", enabled = false },
    { "olimorris/codecompanion.nvim", enabled = false },
}
